Repository TherkuTech/tturl, pull requests merged in 2024-10, with the labels that each got.

#9 added logo
  app/(default)/layout.tsx
  app/[shorturl]/layout.tsx
  app/layout.tsx
  public/assests/logo.png
Labels: gssoc, gssoc-ext, level1, hacktoberfest

#11 fixed:: Meta Tags, Generate Sitemap, and Create robots.txt for SEO Improvement
  app/layout.tsx
  next-sitemap.config.js
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
Labels: gssoc, gssoc-ext, hacktoberfest

#12 Revamped the UI for URL shortener (Closes #1)
  app/(default)/layout.tsx
  app/(default)/page.tsx
  app/[shorturl]/page.tsx
  app/layout.tsx
  components/ui/background-beams-with-collision.tsx
  components/ui/navbar.tsx
  lib/utils.ts
  package-lock.json
  package.json
  pages/api/urlshortener.ts
  postcss.config.js
  providers/backgroundProvider.tsx
  public/mainBG.png
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3

#24 added the dark/light mode feature
  app/(default)/page.tsx
  app/globals.css
  app/layout.tsx
  app/provider.tsx
  components/ui/Themeswitcher.tsx
  components/ui/navbar.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#25 fixed homepage ui
  app/(default)/layout.tsx
  app/(default)/page.tsx
  app/[shorturl]/layout.tsx
  app/layout.tsx
  components/ui/background-beams-with-collision.tsx
  components/ui/navbar.tsx
  providers/backgroundProvider.tsx
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#26 modified nav bar
  components/ui/navbar.tsx
Labels: gssoc, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#31 Added navbar to app/(default)/layout.tsx
  app/(default)/layout.tsx
  app/layout.tsx
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#52 Added clear history Button
  app/(default)/page.tsx
  app/components/History.tsx
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#56 fixed theme bug
  app/(default)/page.tsx
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#58 added scroll bar to the history section issue #53
  app/components/History.tsx
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#59 [URLShortener] Fix duplicate 'www' prefix in shortened URLs
  pages/api/urlshortener.ts
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#64 Feature/about page
  app/about/page.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/navbar.tsx
  package-lock.json
  package.json
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#73 Added url validation issue #62
  app/(default)/page.tsx
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#77 changed the theme Switcher button
  components/ui/Themeswitcher.tsx
  package-lock.json
  package.json
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#78 improved error handling ui
  app/[shorturl]/page.tsx
Labels: gssoc, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#74 Update tailwind.config.ts(Changed the theme to black and purple)
  tailwind.config.ts
Labels: gssoc, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#80 Fixed text color bug Issue no: ##55
  app/(default)/page.tsx
  package-lock.json
  package.json
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#87 Styling added in Navbar
  components/ui/Themeswitcher.tsx
  components/ui/navbar.tsx
  package-lock.json
  tailwind.config.ts
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#92 Made position of button relative and reduced width
  app/(default)/page.tsx
Labels: gssoc, gssoc-ext, level1, hacktoberfest, hacktoberfest-accepted

#76 Add all contributors to readme
  README.md
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#51 Update footer with icons and improved layout
  app/(default)/layout.tsx
  app/(default)/page.tsx
  app/components/footer.jsx
  package-lock.json
  package.json
  public/sitemap-0.xml
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#86 added sample env file
  .env_sample
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#102 Added custom hook to store URLs in local-storage
  app/(default)/page.tsx
  app/[shorturl]/page.tsx
  app/components/History.tsx
  app/hooks/useLocalStorage.ts
  package.json
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3

#104 Improve the history and shortner ui
  app/(default)/page.tsx
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level2

#99 feat: QR Code Generation with Download option
  app/(default)/page.tsx
  lib/modules.d.ts
  package-lock.json
  package.json
Labels: gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3

#130 Footer added
  app/(default)/layout.tsx
Labels: enhancement, gssoc, gssoc-ext, hacktoberfest, hacktoberfest-accepted, level3
